version: "3.9"

networks:
  gin-react-network:
    driver: bridge

volumes:
  gin-react-mySQL:
    name: gin-react-mySQL

services:

  mySQL:
    container_name: gin-react-mySQL
    image: mysql:8.0
    volumes:
      - gin-react-mySQL:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: core2duo
      MYSQL_DATABASE: gin-react
      MYSQL_USER: gin-react-user
      MYSQL_PASSWORD: gin-react-password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - gin-react-network

  phpmyadmin:
    container_name: gin-react-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mySQL
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      # PHP_MY_ADMIN_PASSWORD: phpmyadminPassword
    restart: always
    ports:
      - "5005:80"
    networks:
      - gin-react-network
  # adminer:
  #   container_name: gin-react-adminer
  #   image: adminer
  #   depends_on:
  #     - mySQL
  #   environment:
  #     ADMINER_DEFAULT_DB_DRIVER: mySQL
  #     ADMINER_DEFAULT_DB_HOST: mySQL
  #     ADMINER_DEFAULT_DB_NAME: adminer
  #     ADMINER_DESIGN: nette
  #     ADMINER_PLUGINS: tables-filter tinymce
  #   ports:
  #     - 5006:8080
  #   networks:
  #     - gin-react-network

  # gin-react-phpmyadmin:
  #   container_name: gin-react-phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - gin-react-mySQL
  #   links:
  #     - gin-react-mySQL
  #   environment:
  #     PMA_HOST: gin-react-mySQL
  #     PMA_PORT: 3307
  #     PMA_ARBITRARY: 1
  #     UPLOAD_LIMIT: 50M
  #   restart: always
  #   ports:
  #     - "5558:80"
  #   networks:
  #     - gin-react-network
